services:
  inspection:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: maid-dev
    command: sh -lc "npm run dev:inspection"
    ports:
      - "6969:6969"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  frontend:
    image: maid-dev
    command: sh -lc "npm run dev:frontend -- --host 0.0.0.0 --port 5555 --strictPort"
    ports:
      - "5555:5555"
    environment:
      - VITE_INSPECTION_URL=http://localhost:6969/api
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - inspection

volumes:
  node_modules:


